apiVersion: apps/v1
kind: Deployment
metadata:
  name: testing-cicd-project
spec:
  replicas: 2

  selector:
    matchLabels:
      app: testing-cicd-project

  template:
    metadata:
      labels:
        app: testing-cicd-project

    spec:
      containers:
        - name: testing-cicd-project
          image: nikhleshtest/testing-cicd-project:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 5000
