apiVersion: v1
kind: Service
metadata:
  name: testing-cicd-project
spec:
  selector:
    app: testing-cicd-project

  type: NodePort

  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30080
